name: "CI - Test Features"
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        baseImage:
          - debian:latest
          - fedora:latest
          - alpine:latest
          - archlinux:latest
    steps:
      - uses: actions/checkout@v4

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Generating tests for '${{ matrix.baseImage }}'"
        run: devcontainer features test --skip-scenarios -i ${{ matrix.baseImage }} .